-- CreateEnum
CREATE TYPE "TicketType" AS ENUM ('PC_BUILD', 'PC_REPAIR', 'SYSTEM_DIAGNOSTIC', 'MALWARE_REMOVAL', 'DATA_RECOVERY', 'TRAINING', 'OTHER');

-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN     "type" "TicketType" NOT NULL DEFAULT 'PC_REPAIR';
